### ISSUE TITLE
Question to step4

### ISSUE THREAD

**Issue by JiangTao100** [MichaelTien8901/STM32WINUSB#2]
I have some questions in step4. Do I need to create a Windows Registry  to  meet GUIDs,  or where should  I  modify the source code USB library?  Similarly  which  INF file to modify?  C:\Windows\System32\winusb ?  Thanks!!!

**Comment by MichaelTien8901** [comment]
Modify descriptor in usbd_desc.c.  Change device guid sring to match your guid in INF.
